### ISSUE TITLE
Error in AcceptAnyWhiteListPlugin, init method is missing

### ISSUE THREAD

**Issue by marcosnobrega** [fogbow/fogbow-rendezvous#43]
2016-08-04 16:31:59 WARN  Main:53 - White list plugin not specified in the properties. Failing back to AcceptAnyWhiteListPlugin
java.lang.NoSuchMethodException: org.fogbowcloud.rendezvous.core.plugins.whitelist.AcceptAnyWhiteListPlugin.<init>(java.util.Properties)
	at java.lang.Class.getConstructor0(Class.java:2902)
	at java.lang.Class.getConstructor(Class.java:1731)
	at org.fogbowcloud.rendezvous.xmpp.Main.createInstance(Main.java:77)
	at org.fogbowcloud.rendezvous.xmpp.Main.initializeRendezvousXMPPComponent(Main.java:50)
	at org.fogbowcloud.rendezvous.xmpp.Main.main(Main.java:157)

**Comment by thiagomanel** [comment]
it was closed by commit e0ce2a54945ff57e33d7a5cbbc123258a38f7c1f
